const BASE_API_URL = 'https://mindwise-main.vercel.app/api';

export const ENV = {
  API_URL: BASE_API_URL,
  ONESIGNAL_APP_ID: 'f7ec6e56-2baf-4220-a772-1754ae26d062',
} as const;

export const API_ENDPOINTS = {
  SIGNUP: `${BASE_API_URL}/signup-with-password`,
  LOGIN: `${BASE_API_URL}/login-with-password`,
  BUY_SUBSCRIPTION: `${BASE_API_URL}/buy-subscription`,
  LOGOUT: `${BASE_API_URL}/logout`,
  FORGOT_PASSWORD: `${BASE_API_URL}/forgot-password`,
  VERIFY_FORGOT_PASSWORD: `${BASE_API_URL}/verify-forgot-password`,
  CHANGE_FORGOTTEN_PASSWORD: `${BASE_API_URL}/change-forgotten-password`,
  PROFILE: `${BASE_API_URL}/profile`,
  CONTACTS: `${BASE_API_URL}/contacts`,
  EMERGENCY_CONTACT: `${BASE_API_URL}/emergency-contact`,
  PROGRESS: `${BASE_API_URL}/progress`,
  LETTER_FROM_FUTURE_SELF: `${BASE_API_URL}/letter-from-future-self`,
  NOTIFICATIONS: `${BASE_API_URL}/notifications`,
  NOTIFICATION_SETTINGS: `${BASE_API_URL}/notification-settings`,
  NOTIFICATION_TOKEN: `${BASE_API_URL}/notification-token`,
  SHARING_PERMISSIONS: `${BASE_API_URL}/sharing-permissions`,
  DIARY: `${BASE_API_URL}/diary`,
  TODAY_STATUS: `${BASE_API_URL}/today-status`,
  PROGRESS_TRACKING: `${BASE_API_URL}/progress-tracking`,
  WEEKLY_REVIEW: `${BASE_API_URL}/weekly-review`,
  TREATMENT_PLAN: `${BASE_API_URL}/treatment-plan`,
  PRE_TREATMENT_STATE: `${BASE_API_URL}/pre-treatment-state`,
  GOALS: `${BASE_API_URL}/goals`,
  STRENGTHS_AND_RESOURCES: `${BASE_API_URL}/strengths-and-resources`,
  SUDS_CHECKIN: (date: string) => `${BASE_API_URL}/suds-checkin/${date}`,
  SUDS_LIST: `${BASE_API_URL}/suds-list`,
  SUDS_CALENDAR: (month: string) => `${BASE_API_URL}/suds-calendar/${month}`,
  SUDS_COPING_PLAN: `${BASE_API_URL}/suds-coping-plan`,
  STUNWAVE: `${BASE_API_URL}/stunwave`,
  STUNWAVE_BY_ID: (id: string) => `${BASE_API_URL}/stunwave/${id}`,
  EMOTIONS_WHEEL_REFLECTIONS: `${BASE_API_URL}/emotions-wheel-reflections`,
  EMOTIONS_WHEEL_REFLECTIONS_BY_ID: (id: string) => `${BASE_API_URL}/emotions-wheel-reflections/${id}`,
  EMOTIONS_TRACKING: (date: string) => `${BASE_API_URL}/emotions-tracking/${date}`,
  PRACTICE_WITH_OTHERS: `${BASE_API_URL}/practice-with-others`,
  PRACTICE_WITH_OTHERS_BY_ID: (id: string) => `${BASE_API_URL}/practice-with-others/${id}`,
  PROBLEM_SOLVING: `${BASE_API_URL}/problem-solving`,
  PROBLEM_SOLVING_BY_ID: (id: string) => `${BASE_API_URL}/problem-solving/${id}`,
  DIALECTICAL_REFRAMING: `${BASE_API_URL}/dialectical-reframing`,
  DIALECTICAL_REFRAMING_BY_ID: (id: string) => `${BASE_API_URL}/dialectical-reframing/${id}`,
  EXPLORING_PERSPECTIVES: `${BASE_API_URL}/exploring-perspectives`,
  EXPLORING_PERSPECTIVES_BY_ID: (id: string) => `${BASE_API_URL}/exploring-perspectives/${id}`,
  PLEASE: `${BASE_API_URL}/please`,
  PLEASE_BY_ID: (id: string) => `${BASE_API_URL}/please/${id}`,
  SELF_CARE_REFLECTION: `${BASE_API_URL}/self-care-reflection`,
  SELF_CARE_REFLECTION_BY_ID: (id: string) => `${BASE_API_URL}/self-care-reflection/${id}`,
  CHECK_THE_FACTS: `${BASE_API_URL}/check-the-facts`,
  CHECK_THE_FACTS_BY_ID: (id: string) => `${BASE_API_URL}/check-the-facts/${id}`,
  RECOGNIZING_DIALECTICAL_DILEMMAS: `${BASE_API_URL}/recognizing-dialectical-dilemmas`,
  RECOGNIZING_DIALECTICAL_DILEMMAS_BY_ID: (id: string) => `${BASE_API_URL}/recognizing-dialectical-dilemmas/${id}`,
  ACCEPTANCE_AND_CHANGE: `${BASE_API_URL}/acceptance-and-change`,
  ACCEPTANCE_AND_CHANGE_BY_ID: (id: string) => `${BASE_API_URL}/acceptance-and-change/${id}`,
  HERE_AND_NOW: `${BASE_API_URL}/here-and-now`,
  HERE_AND_NOW_BY_ID: (id: string) => `${BASE_API_URL}/here-and-now/${id}`,
  WISE_MIND: `${BASE_API_URL}/wise-mind`,
  WISE_MIND_BY_ID: (id: string) => `${BASE_API_URL}/wise-mind/${id}`,
  PAST_DECISIONS: `${BASE_API_URL}/past-decisions`,
  PAST_DECISIONS_BY_ID: (id: string) => `${BASE_API_URL}/past-decisions/${id}`,
  SELF_REFLECTION: `${BASE_API_URL}/self-reflection`,
  SELF_REFLECTION_BY_ID: (id: string) => `${BASE_API_URL}/self-reflection/${id}`,
  VALIDATION_PRACTICE: `${BASE_API_URL}/validation-practice`,
  VALIDATION_PRACTICE_BY_ID: (id: string) => `${BASE_API_URL}/validation-practice/${id}`,
  THINK: `${BASE_API_URL}/think`,
  THINK_BY_ID: (id: string) => `${BASE_API_URL}/think/${id}`,
  CLARIFY_YOUR_GOALS: `${BASE_API_URL}/clarify-your-goals`,
  CLARIFY_YOUR_GOALS_BY_ID: (id: string) => `${BASE_API_URL}/clarify-your-goals/${id}`,
  PLAN_YOUR_RESPONSE: `${BASE_API_URL}/plan-your-response`,
  PLAN_YOUR_RESPONSE_BY_ID: (id: string) => `${BASE_API_URL}/plan-your-response/${id}`,
  GIVE_REFRAMING: `${BASE_API_URL}/give-reframing`,
  GIVE_REFRAMING_BY_ID: (id: string) => `${BASE_API_URL}/give-reframing/${id}`,
  GIVE_PRACTICE: `${BASE_API_URL}/give-practice`,
  GIVE_PRACTICE_BY_ID: (id: string) => `${BASE_API_URL}/give-practice/${id}`,
  START_SMALL: `${BASE_API_URL}/start-small`,
  START_SMALL_BY_ID: (id: string) => `${BASE_API_URL}/start-small/${id}`,
  FAST_PLAN: `${BASE_API_URL}/fast-plan`,
  FAST_PLAN_BY_ID: (id: string) => `${BASE_API_URL}/fast-plan/${id}`,
  DEAR_MAN: `${BASE_API_URL}/dear-man`,
  DEAR_MAN_BY_ID: (id: string) => `${BASE_API_URL}/dear-man/${id}`,
  LOVING_KINDNESS: `${BASE_API_URL}/loving-kindness`,
  LOVING_KINDNESS_BY_ID: (id: string) => `${BASE_API_URL}/loving-kindness/${id}`,
  REFRAME_NEGATIVE_SELF_TALK: `${BASE_API_URL}/reframe-negative-self-talk`,
  REFRAME_NEGATIVE_SELF_TALK_BY_ID: (id: string) => `${BASE_API_URL}/reframe-negative-self-talk/${id}`,
  SELF_TALK_TOOLKIT: `${BASE_API_URL}/self-talk-toolkit`,
  SELF_TALK_TOOLKIT_BY_ID: (id: string) => `${BASE_API_URL}/self-talk-toolkit/${id}`,
  SELF_VALIDATION_PRACTICE: `${BASE_API_URL}/self-validation-practice`,
  SELF_VALIDATION_PRACTICE_BY_ID: (id: string) => `${BASE_API_URL}/self-validation-practice/${id}`,
  ORIGINS: `${BASE_API_URL}/origins`,
  ORIGINS_BY_ID: (id: string) => `${BASE_API_URL}/origins/${id}`,
  IDENTIFY_EMOTIONAL_URGES: `${BASE_API_URL}/identify-emotional-urges`,
  IDENTIFY_EMOTIONAL_URGES_BY_ID: (id: string) => `${BASE_API_URL}/identify-emotional-urges/${id}`,
  GRACE: `${BASE_API_URL}/grace`,
  SIGN_COMMITMENT: `${BASE_API_URL}/sign-commitment`,
} as const;
