import React from 'react';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import { HomeStackParams } from './types';
import Home from '@features/home/screens/index';
import Plan from '@features/plan/screens/index';
import Learn from '@features/learn/screens/index';
import UnderstandEmotionsLearnScreen from '@features/learn/screens/UnderstandEmotions';
import RegulateEmotionsScreen from '@features/learn/screens/RegulateEmotions';
import EmotionsWheelScreen from '@features/learn/screens/EmotionsWheel';
import EmotionsWheelExercisesScreen from '@features/learn/screens/EmotionsWheelExercises';
import NameYourEmotionsScreen from '@features/learn/screens/NameYourEmotions';
import EmotionsTrackerScreen from '@features/learn/screens/EmotionsTracker';
import PracticeWithOthersScreen from '@features/learn/screens/PracticeWithOthers';
import AboutSUDSScreen from '@features/learn/screens/AboutSUDS';
import SUDSExercisesScreen from '@features/learn/screens/SUDSExercises';
import SUDSCheckInScreen from '@features/learn/screens/SUDSCheckIn';
import SUDSCopingPlanScreen from '@features/learn/screens/SUDSCopingPlan';
import AboutSTUNWAVEScreen from '@features/learn/screens/AboutSTUNWAVE';
import STUNWAVEExercisesScreen from '@features/learn/screens/STUNWAVEExercises';
import STUNWAVECheckInScreen from '@features/learn/screens/STUNWAVECheckIn';
import STUNWAVEEntriesScreen from '@features/learn/screens/STUNWAVEEntries';
import CheckTheFactsScreen from '@features/learn/screens/CheckTheFacts';
import CheckTheFactsExercisesScreen from '@features/learn/screens/CheckTheFactsExercises';
import CheckTheFactsFindingScreen from '@features/learn/screens/CheckTheFactsFinding';
import CheckTheFactsEntriesScreen from '@features/learn/screens/CheckTheFactsEntries';
import ChainAnalysisScreen from '@features/learn/screens/ChainAnalysis';
import ChainAnalysisExercisesScreen from '@features/learn/screens/ChainAnalysisExercises';
import GuidedChainAnalysisScreen from '@features/learn/screens/GuidedChainAnalysis';
import ChainAnalysisCompleteScreen from '@features/learn/screens/ChainAnalysisComplete';
import SelfCarePleaseScreen from '@features/learn/screens/SelfCarePlease';
import SelfCarePleaseExercisesScreen from '@features/learn/screens/SelfCarePleaseExercises';
import SelfCarePleasePlanScreen from '@features/learn/screens/SelfCarePleasePlan';
import SelfCarePleaseEntriesScreen from '@features/learn/screens/SelfCarePleaseEntries';
import SelfCarePleaseReflectionScreen from '@features/learn/screens/SelfCarePleaseReflection';
import SelfCarePleaseReflectionEntriesScreen from '@features/learn/screens/SelfCarePleaseReflectionEntries';
import DialecticalThinkingScreen from '@features/learn/screens/DialecticalThinking';
import DialecticalThinkingExercisesScreen from '@features/learn/screens/DialecticalThinkingExercises';
import DialecticalThinkingReframingScreen from '@features/learn/screens/DialecticalThinkingReframing';
import DialecticalThinkingEntriesScreen from '@features/learn/screens/DialecticalThinkingEntries';
import DialecticalThinkingExploringPerspectivesScreen from '@features/learn/screens/DialecticalThinkingExploringPerspectives';
import DialecticalThinkingPerspectiveEntriesScreen from '@features/learn/screens/DialecticalThinkingPerspectiveEntries';
import ProblemSolvingScreen from '@features/learn/screens/ProblemSolving';
import ProblemSolvingExerciseScreen from '@features/learn/screens/ProblemSolvingExercise';
import ProblemSolvingEntriesScreen from '@features/learn/screens/ProblemSolvingEntries';
import ProblemSolvingEntryDetailScreen from '@features/learn/screens/ProblemSolvingEntryDetail';
import ImproveInterpersonalEffectivenessScreen from '@features/learn/screens/ImproveInterpersonalEffectiveness';
import BuildDistressToleranceScreen from '@features/learn/screens/BuildDistressTolerance';
import BuildSelfLoveScreen from '@features/learn/screens/BuildSelfLove';
import SelfDiscoveryScreen from '@features/learn/screens/SelfDiscovery';
import SelfDiscoveryExercisesScreen from '@features/learn/screens/SelfDiscoveryExercises';
import SelfDiscoveryOriginsScreen from '@features/learn/screens/SelfDiscoveryOrigins';
import SelfDiscoveryOriginEntriesScreen from '@features/learn/screens/SelfDiscoveryOriginEntries';
import PositiveSelfTalkScreen from '@features/learn/screens/PositiveSelfTalk';
import PositiveSelfTalkExercisesScreen from '@features/learn/screens/PositiveSelfTalkExercises';
import ReframeNegativeSelfTalkScreen from '@features/learn/screens/ReframeNegativeSelfTalk';
import ReframeNegativeSelfTalkEntriesScreen from '@features/learn/screens/ReframeNegativeSelfTalkEntries';
import SelfTalkToolkitScreen from '@features/learn/screens/SelfTalkToolkit';
import SelfTalkToolkitEntriesScreen from '@features/learn/screens/SelfTalkToolkitEntries';
import SelfValidationScreen from '@features/learn/screens/SelfValidation';
import SelfValidationExercisesScreen from '@features/learn/screens/SelfValidationExercises';
import SelfValidationPracticeScreen from '@features/learn/screens/SelfValidationPractice';
import SelfValidationPracticeEntriesScreen from '@features/learn/screens/SelfValidationPracticeEntries';
import TIPPScreen from '@features/learn/screens/TIPP';
import TIPPExercisesScreen from '@features/learn/screens/TIPPExercises';
import STOPScreen from '@features/learn/screens/STOP';
import STOPExercisesScreen from '@features/learn/screens/STOPExercises';
import ReflectivePracticeScreen from '@features/learn/screens/ReflectivePractice';
import ReflectivePracticeEntriesScreen from '@features/learn/screens/ReflectivePracticeEntries';
import StopDrillScreen from '@features/learn/screens/StopDrill';
import StopDrillEntriesScreen from '@features/learn/screens/StopDrillEntries';
import StopDrillEntryScreen from '@features/learn/screens/StopDrillEntry';
import MindfulPauseTimerScreen from '@features/learn/screens/MindfulPauseTimer';
import MindfulPauseEntryScreen from '@features/learn/screens/MindfulPauseEntry';
import RolePlayExerciseScreen from '@features/learn/screens/RolePlayExercise';
import RolePlayEntryScreen from '@features/learn/screens/RolePlayEntry';
import InterpersonalGoalsScreen from '@features/learn/screens/InterpersonalGoals';
import InterpersonalGoalsExercisesScreen from '@features/learn/screens/InterpersonalGoalsExercises';
import ClarifyYourGoalsScreen from '@features/learn/screens/ClarifyYourGoals';
import ClarifyYourGoalsEntriesScreen from '@features/learn/screens/ClarifyYourGoalsEntries';
import PlanYourResponseScreen from '@features/learn/screens/PlanYourResponse';
import PlanYourResponseEntriesScreen from '@features/learn/screens/PlanYourResponseEntries';
import ThinkScreen from '@features/learn/screens/Think';
import ThinkExercisesScreen from '@features/learn/screens/ThinkExercises';
import CommunicateWithThinkScreen from '@features/learn/screens/CommunicateWithThink';
import ThinkEntriesScreen from '@features/learn/screens/ThinkEntries';
import ValidatingOthersScreen from '@features/learn/screens/ValidatingOthers';
import ValidatingOthersExercisesScreen from '@features/learn/screens/ValidatingOthersExercises';
import SelfReflectionScreen from '@features/learn/screens/SelfReflection';
import SelfReflectionEntriesScreen from '@features/learn/screens/SelfReflectionEntries';
import ValidationPracticeScreen from '@features/learn/screens/ValidationPractice';
import ValidationPracticeEntriesScreen from '@features/learn/screens/ValidationPracticeEntries';
import SelfSoothingScreen from '@features/learn/screens/SelfSoothing';
import SelfSoothingExercisesScreen from '@features/learn/screens/SelfSoothingExercises';
import FiveSensesInventoryScreen from '@features/learn/screens/FiveSensesInventory';
import FiveSensesInventoryEntriesScreen from '@features/learn/screens/FiveSensesInventoryEntries';
import ReflectionJournalScreen from '@features/learn/screens/ReflectionJournal';
import ReflectionJournalEntriesScreen from '@features/learn/screens/ReflectionJournalEntries';
import ImproveScreen from '@features/learn/screens/Improve';
import ImproveExercisesScreen from '@features/learn/screens/ImproveExercises';
import IdentifyTriggersScreen from '@features/learn/screens/IdentifyTriggers';
import IdentifyTriggersEntriesScreen from '@features/learn/screens/IdentifyTriggersEntries';
import CreateAPersonalizedToolkitScreen from '@features/learn/screens/CreateAPersonalizedToolkit';
import CreateAPersonalizedToolkitEntriesScreen from '@features/learn/screens/CreateAPersonalizedToolkitEntries';
import RadicalAcceptanceScreen from '@features/learn/screens/RadicalAcceptance';
import RadicalAcceptanceExercisesScreen from '@features/learn/screens/RadicalAcceptanceExercises';
import RadicalAcceptanceJournalScreen from '@features/learn/screens/RadicalAcceptanceJournal';
import RadicalAcceptanceJournalEntriesScreen from '@features/learn/screens/RadicalAcceptanceJournalEntries';
import RadicalAcceptanceCopingStatementsListScreen from '@features/learn/screens/RadicalAcceptanceCopingStatementsList';
import RadicalAcceptanceCopingStatementsListEntriesScreen from '@features/learn/screens/RadicalAcceptanceCopingStatementsListEntries';
import DifferentActionScreen from '@features/learn/screens/DifferentAction';
import DifferentActionExercisesScreen from '@features/learn/screens/DifferentActionExercises';
import DifferentActionIdentifyEmotionalUrgesScreen from '@features/learn/screens/DifferentActionIdentifyEmotionalUrges';
import DifferentActionIdentifyEmotionalUrgesEntriesScreen from '@features/learn/screens/DifferentActionIdentifyEmotionalUrgesEntries';
import DifferentActionFlashCardPromptsScreen from '@features/learn/screens/DifferentActionFlashCardPrompts';
import HalfSmilingScreen from '@features/learn/screens/HalfSmiling';
import HalfSmilingExercisesScreen from '@features/learn/screens/HalfSmilingExercises';
import HalfSmilingMindfulHalfSmilePracticeScreen from '@features/learn/screens/HalfSmilingMindfulHalfSmilePractice';
import HalfSmilingEmotionMappingScreen from '@features/learn/screens/HalfSmilingEmotionMapping';
import HalfSmilingActionScreen from '@features/learn/screens/HalfSmilingAction';
import HalfSmilingAnchorPromptScreen from '@features/learn/screens/HalfSmilingAnchorPrompt';
import HalfSmilingEntriesScreen from '@features/learn/screens/HalfSmilingEntries';
import BeMindfulScreen from '@features/learn/screens/BeMindful';
import HereAndNowScreen from '@features/learn/screens/HereAndNow';
import HereAndNowExercisesScreen from '@features/learn/screens/HereAndNowExercises';
import DearManScreen from '@features/learn/screens/DearMan';
import DearManExercisesScreen from '@features/learn/screens/DearManExercises';
import DearManEntriesScreen from '@features/learn/screens/DearManEntries';
import FastScreen from '@features/learn/screens/Fast';
import FastExercisesScreen from '@features/learn/screens/FastExercises';
import FastStartSmallScreen from '@features/learn/screens/FastStartSmall';
import FastStartSmallEntriesScreen from '@features/learn/screens/FastStartSmallEntries';
import FastPlanScreen from '@features/learn/screens/FastPlan';
import FastPlanEntriesScreen from '@features/learn/screens/FastPlanEntries';
import GiveScreen from '@features/learn/screens/Give';
import GiveExercisesScreen from '@features/learn/screens/GiveExercises';
import GiveReframingScreen from '@features/learn/screens/GiveReframing';
import GiveReframingEntriesScreen from '@features/learn/screens/GiveReframingEntries';
import GivePracticeScreen from '@features/learn/screens/GivePractice';
import GivePracticeEntriesScreen from '@features/learn/screens/GivePracticeEntries';
import MindfulPresencePracticeScreen from '@features/learn/screens/MindfulPresencePractice';
import MindfulPresencePracticeEntriesScreen from '@features/learn/screens/MindfulPresencePracticeEntries';
import WiseMindScreen from '@features/learn/screens/WiseMind';
import WiseMindExercisesScreen from '@features/learn/screens/WiseMindExercises';
import WiseMindPracticeScreen from '@features/learn/screens/WiseMindPractice';
import WiseMindPracticeEntriesScreen from '@features/learn/screens/WiseMindPracticeEntries';
import WiseMindPracticeEntryDetailScreen from '@features/learn/screens/WiseMindPracticeEntryDetail';
import WiseMindPastDecisionsScreen from '@features/learn/screens/WiseMindPastDecisions';
import WiseMindPastDecisionEntriesScreen from '@features/learn/screens/WiseMindPastDecisionEntries';
import WiseMindPastDecisionEntryDetailScreen from '@features/learn/screens/WiseMindPastDecisionEntryDetail';
import WillingHandsScreen from '@features/learn/screens/WillingHands';
import WillingHandsExercisesScreen from '@features/learn/screens/WillingHandsExercises';
import WillingHandsPracticeScreen from '@features/learn/screens/WillingHandsPractice';
import WillingHandsEntriesScreen from '@features/learn/screens/WillingHandsEntries';
import WillingHandsEntryDetailScreen from '@features/learn/screens/WillingHandsEntryDetail';
import LovingKindnessScreen from '@features/learn/screens/LovingKindness';
import LovingKindnessExercisesScreen from '@features/learn/screens/LovingKindnessExercises';
import LovingKindnessPracticeScreen from '@features/learn/screens/LovingKindnessPractice';
import LovingKindnessPracticeEntriesScreen from '@features/learn/screens/LovingKindnessPracticeEntries';
import LovingKindnessPracticeEntryDetailScreen from '@features/learn/screens/LovingKindnessPracticeEntryDetail';
import MiddlePathScreen from '@features/learn/screens/MiddlePath';
import MiddlePathExercisesScreen from '@features/learn/screens/MiddlePathExercises';
import RecognizingDialecticalDilemmasScreen from '@features/learn/screens/RecognizingDialecticalDilemmas';
import RecognizingDialecticalDilemmasEntriesScreen from '@features/learn/screens/RecognizingDialecticalDilemmasEntries';
import AcceptanceAndChangeScreen from '@features/learn/screens/AcceptanceAndChange';
import AcceptanceAndChangeEntriesScreen from '@features/learn/screens/AcceptanceAndChangeEntries';
import Act from '@features/act/screens/index';
import Account from '@features/account/screens/index';
import Help from '@features/help/screens/index';

import HelpReasonScreen from '@features/help/screens/Reason';
import TutorialIntroScreen from '@features/tutorial/screens/TutorialIntro';
import TutorialScreen from '@features/tutorial/screens/Tutorial';
import { NotificationsScreen } from '@features/notifications/screens/index';
import PreTreatmentScreen from '@features/home/screens/pretreatment/PreTreatment';
import DBTOverviewScreen from '@features/home/screens/pretreatment/DBTOverview';
import UnderstandYourselfScreen from '@features/home/screens/pretreatment/UnderstandYourself';
import UnderstandEmotionsScreen from '@features/home/screens/pretreatment/UnderstandEmotions';
import AboutDBTScreen from '@features/home/screens/pretreatment/AboutDBT';
import DBTSkillsScreen from '@features/home/screens/pretreatment/DBTSkills';
import DBTJourneyScreen from '@features/home/screens/pretreatment/DBTJourney';
import TreatmentAssessmentScreen from '@features/home/screens/pretreatment/TreatmentAssessment';
import StrengthsResourcesScreen from '@features/home/screens/pretreatment/StrengthsResources';
import BuildingCommitmentScreen from '@features/home/screens/pretreatment/BuildingCommitment';
import LetterFromFutureSelfScreen from '@features/home/screens/pretreatment/LetterFromFutureSelf';
import SignYourCommitmentsScreen from '@features/home/screens/pretreatment/SignYourCommitments';
import TreatmentPlanScreen from '@features/home/screens/pretreatment/TreatmentPlan';
import DailyCheckInScreen from '@features/home/screens/dailycheckin/DailyCheckIn';
import TodayCheckInScreen from '@features/home/screens/dailycheckin/TodayCheckIn';
import WeeklyReviewScreen from '@features/home/screens/dailycheckin/WeeklyReview';
import ProgressTrackingScreen from '@features/home/screens/dailycheckin/ProgressTracking';
import Favorites from '@features/account/screens/Favorites';
import Contacts from '@features/account/screens/Contacts';
import Privacy from '@features/account/screens/Privacy';
import Settings from '@features/account/screens/Settings';
import HelpSupport from '@features/account/screens/HelpSupport';


const Stack = createNativeStackNavigator<HomeStackParams>();

export default function HomeNavigator() {
    return (
        <Stack.Navigator screenOptions={{ headerShown: false }} initialRouteName='Home'>
            <Stack.Screen name="Home" component={Home} />

            <Stack.Screen name="TutorialIntro" component={TutorialIntroScreen} />
            <Stack.Screen name="Tutorial" component={TutorialScreen} />

            <Stack.Screen name="Plan" component={Plan} />

            {/* Pre-Treatment Module */}
            <Stack.Screen name="PreTreatment" component={PreTreatmentScreen} />
            <Stack.Screen name="DBTOverview" component={DBTOverviewScreen} />
            <Stack.Screen name="UnderstandYourself" component={UnderstandYourselfScreen} />
            <Stack.Screen name="UnderstandEmotions" component={UnderstandEmotionsScreen} />
            <Stack.Screen name="AboutDBT" component={AboutDBTScreen} />
            <Stack.Screen name="DBTSkills" component={DBTSkillsScreen} />
            <Stack.Screen name="DBTJourney" component={DBTJourneyScreen} />
            <Stack.Screen name="TreatmentAssessment" component={TreatmentAssessmentScreen} />
            <Stack.Screen name="StrengthsResources" component={StrengthsResourcesScreen} />
            <Stack.Screen name="BuildingCommitment" component={BuildingCommitmentScreen} />
            <Stack.Screen name="LetterFromFutureSelf" component={LetterFromFutureSelfScreen} />
            <Stack.Screen name="SignYourCommitments" component={SignYourCommitmentsScreen} />
            <Stack.Screen name="TreatmentPlan" component={TreatmentPlanScreen} />

            {/* Daily Check-In Module */}
            <Stack.Screen name="DailyCheckIn" component={DailyCheckInScreen} />
            <Stack.Screen name="TodayCheckIn" component={TodayCheckInScreen} />
            <Stack.Screen name="WeeklyReview" component={WeeklyReviewScreen} />
            <Stack.Screen name="ProgressTracking" component={ProgressTrackingScreen} />

            {/** Account Module */}
            <Stack.Screen name="Account" component={Account} />
            <Stack.Screen name="Account_Favorites" component={Favorites} />
            <Stack.Screen name="Account_Contacts" component={Contacts} />
            <Stack.Screen name="Account_Privacy" component={Privacy} />
            <Stack.Screen name="Account_Settings" component={Settings} />
            <Stack.Screen name="Account_Help" component={HelpSupport} />

            
            <Stack.Screen name="Learn" component={Learn} />
            <Stack.Screen name="Learn_UnderstandEmotions" component={UnderstandEmotionsLearnScreen} />
            <Stack.Screen name="Learn_RegulateEmotions" component={RegulateEmotionsScreen} />
            <Stack.Screen name="Learn_EmotionsWheel" component={EmotionsWheelScreen} />
            <Stack.Screen name="Learn_EmotionsWheelExercises" component={EmotionsWheelExercisesScreen} />
            <Stack.Screen name="Learn_NameYourEmotions" component={NameYourEmotionsScreen} />
            <Stack.Screen name="Learn_EmotionsTracker" component={EmotionsTrackerScreen} />
            <Stack.Screen name="Learn_PracticeWithOthers" component={PracticeWithOthersScreen} />
            <Stack.Screen name="Learn_AboutSUDS" component={AboutSUDSScreen} />
            <Stack.Screen name="Learn_SUDSExercises" component={SUDSExercisesScreen} />
            <Stack.Screen name="Learn_SUDSCheckIn" component={SUDSCheckInScreen} />
            <Stack.Screen name="Learn_SUDSCopingPlan" component={SUDSCopingPlanScreen} />
            <Stack.Screen name="Learn_AboutSTUNWAVE" component={AboutSTUNWAVEScreen} />
            <Stack.Screen name="Learn_STUNWAVEExercises" component={STUNWAVEExercisesScreen} />
            <Stack.Screen name="Learn_STUNWAVECheckIn" component={STUNWAVECheckInScreen} />
            <Stack.Screen name="Learn_STUNWAVEEntries" component={STUNWAVEEntriesScreen} />
            <Stack.Screen name="Learn_CheckTheFacts" component={CheckTheFactsScreen} />
            <Stack.Screen name="Learn_CheckTheFactsExercises" component={CheckTheFactsExercisesScreen} />
            <Stack.Screen name="Learn_CheckTheFactsFinding" component={CheckTheFactsFindingScreen} />
            <Stack.Screen name="Learn_CheckTheFactsEntries" component={CheckTheFactsEntriesScreen} />
            <Stack.Screen name="Learn_ChainAnalysis" component={ChainAnalysisScreen} />
            <Stack.Screen name="Learn_ChainAnalysisExercises" component={ChainAnalysisExercisesScreen} />
            <Stack.Screen name="Learn_GuidedChainAnalysis" component={GuidedChainAnalysisScreen} />
            <Stack.Screen name="Learn_ChainAnalysisComplete" component={ChainAnalysisCompleteScreen} />
            <Stack.Screen name="Learn_SelfCarePlease" component={SelfCarePleaseScreen} />
            <Stack.Screen name="Learn_SelfCarePleaseExercises" component={SelfCarePleaseExercisesScreen} />
            <Stack.Screen name="Learn_SelfCarePleasePlan" component={SelfCarePleasePlanScreen} />
            <Stack.Screen name="Learn_SelfCarePleaseEntries" component={SelfCarePleaseEntriesScreen} />
            <Stack.Screen name="Learn_SelfCarePleaseReflection" component={SelfCarePleaseReflectionScreen} />
            <Stack.Screen name="Learn_SelfCarePleaseReflectionEntries" component={SelfCarePleaseReflectionEntriesScreen} />
            <Stack.Screen name="Learn_DialecticalThinking" component={DialecticalThinkingScreen} />
            <Stack.Screen name="Learn_DialecticalThinkingExercises" component={DialecticalThinkingExercisesScreen} />
            <Stack.Screen name="Learn_DialecticalThinkingReframing" component={DialecticalThinkingReframingScreen} />
            <Stack.Screen name="Learn_DialecticalThinkingEntries" component={DialecticalThinkingEntriesScreen} />
            <Stack.Screen name="Learn_DialecticalThinkingExploringPerspectives" component={DialecticalThinkingExploringPerspectivesScreen} />
            <Stack.Screen name="Learn_DialecticalThinkingPerspectiveEntries" component={DialecticalThinkingPerspectiveEntriesScreen} />
            <Stack.Screen name="Learn_ProblemSolving" component={ProblemSolvingScreen} />
            <Stack.Screen name="Learn_ProblemSolvingExercise" component={ProblemSolvingExerciseScreen} />
            <Stack.Screen name="Learn_ProblemSolvingEntries" component={ProblemSolvingEntriesScreen} />
            <Stack.Screen name="Learn_ProblemSolvingEntryDetail" component={ProblemSolvingEntryDetailScreen} />
            <Stack.Screen name="Learn_ImproveInterpersonalEffectiveness" component={ImproveInterpersonalEffectivenessScreen} />
            <Stack.Screen name="Learn_BuildDistressTolerance" component={BuildDistressToleranceScreen} />
            <Stack.Screen name="Learn_BuildSelfLove" component={BuildSelfLoveScreen} />
            <Stack.Screen name="Learn_SelfDiscovery" component={SelfDiscoveryScreen} />
            <Stack.Screen name="Learn_SelfDiscoveryExercises" component={SelfDiscoveryExercisesScreen} />
            <Stack.Screen name="Learn_SelfDiscoveryOrigins" component={SelfDiscoveryOriginsScreen} />
            <Stack.Screen name="Learn_SelfDiscoveryOriginEntries" component={SelfDiscoveryOriginEntriesScreen} />
            <Stack.Screen name="Learn_PositiveSelfTalk" component={PositiveSelfTalkScreen} />
            <Stack.Screen name="Learn_PositiveSelfTalkExercises" component={PositiveSelfTalkExercisesScreen} />
            <Stack.Screen name="Learn_ReframeNegativeSelfTalk" component={ReframeNegativeSelfTalkScreen} />
            <Stack.Screen name="Learn_ReframeNegativeSelfTalkEntries" component={ReframeNegativeSelfTalkEntriesScreen} />
            <Stack.Screen name="Learn_SelfTalkToolkit" component={SelfTalkToolkitScreen} />
            <Stack.Screen name="Learn_SelfTalkToolkitEntries" component={SelfTalkToolkitEntriesScreen} />
            <Stack.Screen name="Learn_SelfValidation" component={SelfValidationScreen} />
            <Stack.Screen name="Learn_SelfValidationExercises" component={SelfValidationExercisesScreen} />
            <Stack.Screen name="Learn_SelfValidationPractice" component={SelfValidationPracticeScreen} />
            <Stack.Screen name="Learn_SelfValidationPracticeEntries" component={SelfValidationPracticeEntriesScreen} />
            <Stack.Screen name="Learn_TIPP" component={TIPPScreen} />
            <Stack.Screen name="Learn_TIPPExercises" component={TIPPExercisesScreen} />
            <Stack.Screen name="Learn_STOP" component={STOPScreen} />
            <Stack.Screen name="Learn_STOPExercises" component={STOPExercisesScreen} />
            <Stack.Screen name="Learn_ReflectivePractice" component={ReflectivePracticeScreen} />
            <Stack.Screen name="Learn_ReflectivePracticeEntries" component={ReflectivePracticeEntriesScreen} />
            <Stack.Screen name="Learn_StopDrill" component={StopDrillScreen} />
            <Stack.Screen name="Learn_StopDrillEntries" component={StopDrillEntriesScreen} />
            <Stack.Screen name="Learn_StopDrillEntry" component={StopDrillEntryScreen} />
            <Stack.Screen name="Learn_InterpersonalGoals" component={InterpersonalGoalsScreen} />
            <Stack.Screen name="Learn_InterpersonalGoalsExercises" component={InterpersonalGoalsExercisesScreen} />
            <Stack.Screen name="Learn_ClarifyYourGoals" component={ClarifyYourGoalsScreen} />
            <Stack.Screen name="Learn_ClarifyYourGoalsEntries" component={ClarifyYourGoalsEntriesScreen} />
            <Stack.Screen name="Learn_PlanYourResponse" component={PlanYourResponseScreen} />
            <Stack.Screen name="Learn_PlanYourResponseEntries" component={PlanYourResponseEntriesScreen} />
            <Stack.Screen name="Learn_Think" component={ThinkScreen} />
            <Stack.Screen name="Learn_ThinkExercises" component={ThinkExercisesScreen} />
            <Stack.Screen name="Learn_CommunicateWithThink" component={CommunicateWithThinkScreen} />
            <Stack.Screen name="Learn_ThinkEntries" component={ThinkEntriesScreen} />
            <Stack.Screen name="Learn_ValidatingOthers" component={ValidatingOthersScreen} />
            <Stack.Screen name="Learn_ValidatingOthersExercises" component={ValidatingOthersExercisesScreen} />
            <Stack.Screen name="Learn_SelfReflection" component={SelfReflectionScreen} />
            <Stack.Screen name="Learn_SelfReflectionEntries" component={SelfReflectionEntriesScreen} />
            <Stack.Screen name="Learn_ValidationPractice" component={ValidationPracticeScreen} />
            <Stack.Screen name="Learn_ValidationPracticeEntries" component={ValidationPracticeEntriesScreen} />
            <Stack.Screen name="Learn_SelfSoothing" component={SelfSoothingScreen} />
            <Stack.Screen name="Learn_SelfSoothingExercises" component={SelfSoothingExercisesScreen} />
            <Stack.Screen name="Learn_FiveSensesInventory" component={FiveSensesInventoryScreen} />
            <Stack.Screen name="Learn_FiveSensesInventoryEntries" component={FiveSensesInventoryEntriesScreen} />
            <Stack.Screen name="Learn_ReflectionJournal" component={ReflectionJournalScreen} />
            <Stack.Screen name="Learn_ReflectionJournalEntries" component={ReflectionJournalEntriesScreen} />
            <Stack.Screen name="Learn_Improve" component={ImproveScreen} />
            <Stack.Screen name="Learn_ImproveExercises" component={ImproveExercisesScreen} />
            <Stack.Screen name="Learn_IdentifyTriggers" component={IdentifyTriggersScreen} />
            <Stack.Screen name="Learn_IdentifyTriggersEntries" component={IdentifyTriggersEntriesScreen} />
            <Stack.Screen name="Learn_CreateAPersonalizedToolkit" component={CreateAPersonalizedToolkitScreen} />
            <Stack.Screen name="Learn_CreateAPersonalizedToolkitEntries" component={CreateAPersonalizedToolkitEntriesScreen} />
            <Stack.Screen name="Learn_RadicalAcceptance" component={RadicalAcceptanceScreen} />
            <Stack.Screen name="Learn_RadicalAcceptanceExercises" component={RadicalAcceptanceExercisesScreen} />
            <Stack.Screen name="Learn_RadicalAcceptanceJournal" component={RadicalAcceptanceJournalScreen} />
            <Stack.Screen name="Learn_RadicalAcceptanceJournalEntries" component={RadicalAcceptanceJournalEntriesScreen} />
            <Stack.Screen name="Learn_RadicalAcceptanceCopingStatementsList" component={RadicalAcceptanceCopingStatementsListScreen} />
            <Stack.Screen name="Learn_RadicalAcceptanceCopingStatementsListEntries" component={RadicalAcceptanceCopingStatementsListEntriesScreen} />
            <Stack.Screen name="Learn_DifferentAction" component={DifferentActionScreen} />
            <Stack.Screen name="Learn_DifferentActionExercises" component={DifferentActionExercisesScreen} />
            <Stack.Screen name="Learn_DifferentActionIdentifyEmotionalUrges" component={DifferentActionIdentifyEmotionalUrgesScreen} />
            <Stack.Screen name="Learn_DifferentActionIdentifyEmotionalUrgesEntries" component={DifferentActionIdentifyEmotionalUrgesEntriesScreen} />
            <Stack.Screen name="Learn_DifferentActionFlashCardPrompts" component={DifferentActionFlashCardPromptsScreen} />
            <Stack.Screen name="Learn_HalfSmiling" component={HalfSmilingScreen} />
            <Stack.Screen name="Learn_HalfSmilingExercises" component={HalfSmilingExercisesScreen} />
            <Stack.Screen name="Learn_HalfSmilingMindfulHalfSmilePractice" component={HalfSmilingMindfulHalfSmilePracticeScreen} />
            <Stack.Screen name="Learn_HalfSmilingEmotionMapping" component={HalfSmilingEmotionMappingScreen} />
            <Stack.Screen name="Learn_HalfSmilingAction" component={HalfSmilingActionScreen} />
            <Stack.Screen name="Learn_HalfSmilingAnchorPrompt" component={HalfSmilingAnchorPromptScreen} />
            <Stack.Screen name="Learn_HalfSmilingEntries" component={HalfSmilingEntriesScreen} />
            <Stack.Screen name="Learn_BeMindful" component={BeMindfulScreen} />
            <Stack.Screen name="Learn_HereAndNow" component={HereAndNowScreen} />
            <Stack.Screen name="Learn_HereAndNowExercises" component={HereAndNowExercisesScreen} />
            <Stack.Screen name="Learn_DearMan" component={DearManScreen} />
            <Stack.Screen name="Learn_DearManExercises" component={DearManExercisesScreen} />
            <Stack.Screen name="Learn_DearManEntries" component={DearManEntriesScreen} />
            <Stack.Screen name="Learn_Fast" component={FastScreen} />
            <Stack.Screen name="Learn_FastExercises" component={FastExercisesScreen} />
            <Stack.Screen name="Learn_FastStartSmall" component={FastStartSmallScreen} />
            <Stack.Screen name="Learn_FastStartSmallEntries" component={FastStartSmallEntriesScreen} />
            <Stack.Screen name="Learn_FastPlan" component={FastPlanScreen} />
            <Stack.Screen name="Learn_FastPlanEntries" component={FastPlanEntriesScreen} />
            <Stack.Screen name="Learn_Give" component={GiveScreen} />
            <Stack.Screen name="Learn_GiveExercises" component={GiveExercisesScreen} />
            <Stack.Screen name="Learn_GiveReframing" component={GiveReframingScreen} />
            <Stack.Screen name="Learn_GiveReframingEntries" component={GiveReframingEntriesScreen} />
            <Stack.Screen name="Learn_GivePractice" component={GivePracticeScreen} />
            <Stack.Screen name="Learn_GivePracticeEntries" component={GivePracticeEntriesScreen} />
            <Stack.Screen name="Learn_MindfulPresencePractice" component={MindfulPresencePracticeScreen} />
            <Stack.Screen name="Learn_MindfulPresencePracticeEntries" component={MindfulPresencePracticeEntriesScreen} />
            <Stack.Screen name="Learn_MindfulPauseTimer" component={MindfulPauseTimerScreen} />
            <Stack.Screen name="Learn_MindfulPauseEntry" component={MindfulPauseEntryScreen} />
            <Stack.Screen name="Learn_RolePlayExercise" component={RolePlayExerciseScreen} />
            <Stack.Screen name="Learn_RolePlayEntry" component={RolePlayEntryScreen} />
            <Stack.Screen name="Learn_WiseMind" component={WiseMindScreen} />
            <Stack.Screen name="Learn_WiseMindExercises" component={WiseMindExercisesScreen} />
            <Stack.Screen name="Learn_WiseMindPractice" component={WiseMindPracticeScreen} />
            <Stack.Screen name="Learn_WiseMindPracticeEntries" component={WiseMindPracticeEntriesScreen} />
            <Stack.Screen name="Learn_WiseMindPracticeEntryDetail" component={WiseMindPracticeEntryDetailScreen} />
            <Stack.Screen name="Learn_WiseMindPastDecisions" component={WiseMindPastDecisionsScreen} />
            <Stack.Screen name="Learn_WiseMindPastDecisionEntries" component={WiseMindPastDecisionEntriesScreen} />
            <Stack.Screen name="Learn_WiseMindPastDecisionEntryDetail" component={WiseMindPastDecisionEntryDetailScreen} />
            <Stack.Screen name="Learn_WillingHands" component={WillingHandsScreen} />
            <Stack.Screen name="Learn_WillingHandsExercises" component={WillingHandsExercisesScreen} />
            <Stack.Screen name="Learn_WillingHandsPractice" component={WillingHandsPracticeScreen} />
            <Stack.Screen name="Learn_WillingHandsEntries" component={WillingHandsEntriesScreen} />
            <Stack.Screen name="Learn_WillingHandsEntryDetail" component={WillingHandsEntryDetailScreen} />
            <Stack.Screen name="Learn_LovingKindness" component={LovingKindnessScreen} />
            <Stack.Screen name="Learn_LovingKindnessExercises" component={LovingKindnessExercisesScreen} />
            <Stack.Screen name="Learn_LovingKindnessPractice" component={LovingKindnessPracticeScreen} />
            <Stack.Screen name="Learn_LovingKindnessPracticeEntries" component={LovingKindnessPracticeEntriesScreen} />
            <Stack.Screen name="Learn_LovingKindnessPracticeEntryDetail" component={LovingKindnessPracticeEntryDetailScreen} />
            <Stack.Screen name="Learn_MiddlePath" component={MiddlePathScreen} />
            <Stack.Screen name="Learn_MiddlePathExercises" component={MiddlePathExercisesScreen} />
            <Stack.Screen name="Learn_RecognizingDialecticalDilemmas" component={RecognizingDialecticalDilemmasScreen} />
            <Stack.Screen name="Learn_RecognizingDialecticalDilemmasEntries" component={RecognizingDialecticalDilemmasEntriesScreen} />
            <Stack.Screen name="Learn_AcceptanceAndChange" component={AcceptanceAndChangeScreen} />
            <Stack.Screen name="Learn_AcceptanceAndChangeEntries" component={AcceptanceAndChangeEntriesScreen} />
            <Stack.Screen name="Act" component={Act} />
            <Stack.Screen name="Help" component={Help} />
            <Stack.Screen name="Help_Reason" component={HelpReasonScreen} />
            <Stack.Screen name="Notifications" component={NotificationsScreen} />
        </Stack.Navigator>
    );
}
